### ISSUE TITLE
Profile List

### ISSUE THREAD

**Issue by ShieldsJohn** [ShieldsJohn/drf_api#4]
As a developer, I want to be able to view a list of profiles.

### Acceptance Criteria:

- I can view a list of profiles.

### Tasks

- [x] Create a ProfileList view
- [x] Create a model serializer for Profile
- [x] Test the list is generated.
